### ISSUE TITLE
Bug - PFD Pitch Trim Warnings Cycling Rapidly 

### ISSUE THREAD

**Issue by Axeinator** [legoboyvdlp/A320-family#176] opened 2020-08-18 14:49 UTC
**Describe the bug**
When All FACs, ELACs, and SECs are disabled, the PFD Warnings "Use MAN Pitch Trim" and "MAN Pitch Trim Only" repeatedly cycle and flash on the PFD, like in the GIF attached. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Be in the air, with autopilot on. 
2. Disable all FACs, ELACs and SECs, so that the autopilot disconnects. 
3. The PFD will show both "Use MAN Pitch Trim" and "MAN Pitch Trim Only"

**Expected behaviour**
According to posts on Aviation Stack Exchange, what should happen is that only "MAN Pitch Trim Only" should display on the PFD. The aircraft basically goes into a mechanical mode, pitch is controlled by the trim wheel and roll and yaw is the rudder pedals. 
[https://aviation.stackexchange.com/q/36268/52016](https://aviation.stackexchange.com/q/36268/52016)

**Screenshots**
![Screen-Recording-Of-Issue](https://user-images.githubusercontent.com/33792363/90527347-10d3fa80-e137-11ea-9633-30031c57a094.gif)

**System (please complete the following information):**
 - OS: Mac OS 11.0 Beta
 - FlightGear version: 2020.1.3

**Comment by Octal450** [comment] 2020-08-18 16:08
This is since @legoboyvdlp 's changes to the fbw logic

**Comment by legoboyvdlp** [comment] 2020-08-18 16:18
I tested this very situation, so I doubt it is caused by this. Unless there was a subsequent set of changes?

**Comment by Octal450** [comment] 2020-08-18 16:33
The only thing that *should* be allowed to write to the law property (which is what should be used to decide what is shown on the PFD) should be it-fbw.nas.

Could check if it was written to anywhere else.

**Comment by legoboyvdlp** [comment] 2020-08-18 16:59
Thanks --> it's been fixed now :) 
@Axeinator 

The issue was that the legacy code did not consider the flight computer failures, so would try to reset it in the case of total failure.

**Closed as completed by legoboyvdlp** 2020-08-18 16:59 UTC
Labels: bug
