### ISSUE TITLE
Bug - Weird stall behavior

### ISSUE THREAD

**Issue by leEduardo** [legoboyvdlp/A320-family#249] opened 2021-08-08 20:26 UTC
**Describe the bug**
When the aircraft stalls from a high angle of attack, it immediately gains insane forward acceleration and quickly recovers from the stall climbing like a rocket once the vertical speed is showing -3000 ft/min or so, even if the pitch is maintained at the exact same angle it was at the moment of the stall.

It seems like the physics model uses only the vertical speed as a parameter for forward acceleration and does not consider the aircraft pitch; I wouldn't imagine any plane would be able to power-climb out of a deep stall with an angle of attack of 90 degrees.

**To Reproduce**
Steps to reproduce the behaviour:
1. While in flight, select Idle Thrust and apply full aft pressure on the sidestick;
2. The airspeed will decrease and the altitude will increase rapidly;
3. Once the airspeed reaches alpha-floor, thrust will be automatically set to alpha-floor power, as expected;
4. The pitch of the aicraft, though, will remain unchanged at +30deg. As a result of this, even with alpha-floor power, the airspeed will continue to decrease well into the red bar, down to 100kts (note that the aircraft is half-full);
5. Once the airspeed is at around 100kts, the plane will magically accelerate forward to an airspeed of ~170kt, quickly climbing like a rocket; the pitch is still at +30deg.

**Expected behaviour**
The upper pitch limit should be lowered if airspeed and power are in alpha-floor and the plane continues to lose speed, so as to maintain minimum flyable speed at maximum power. See: https://youtu.be/E-PsdxhEs-s?t=353

**Screenshots**

**System (please complete the following information):**
 - OS: Lubuntu 20.04
 - FlightGear version: 2020.3.9
 - A320 Version: 3D

**Comment by legoboyvdlp** [comment] 2021-08-08 20:27
Thanks for the report. This is the reason why 3D is not yet merged, it is nowhere near finished. @Octal450 will fix that before merging.

**Closed as completed by legoboyvdlp** 2021-08-08 20:27 UTC
Labels: bug

**Comment by leEduardo** [comment] 2021-08-08 20:39
> Thanks for the report. This is the reason why 3D is not yet merged, it is nowhere near finished. @Octal450 will fix that before merging.

Well, I just tested and the same thing happens in the dev aircraft, the pitch limit stays at +30deg all the way... the only difference is that in dev the aircraft falls like a brick to the ground, and in the 3D one it rockets into a steep climb. Maybe we could leave this open?

**Comment by Octal450** [comment] 2021-08-08 21:30
@leEduardo the issue is because the extreme stall condition angle of attack isn't computed yet. I will be doing that once I am statisifed with the normal lift vs alpha table.

Vertical speed is not used at all in the flight dynamics, btw.

The pitch stall FlyByWire law is not there yet either, so that is why the pitch tries to stay where it is.

So not really a bug, more like, a to-be-done.

Kind Regards,
Josh
